### ISSUE TITLE
Password policy not respected when creating a new account

### ISSUE THREAD

**Issue by MarneeDear** [aws/aws-aspnet-cognito-identity-provider#133]
May be related to #116 

I get an error about not meeting the password complexity requirements, but I don't have any.

Here is my password policy

![image](https://user-images.githubusercontent.com/5660628/66882676-37a62b00-ef80-11e9-8702-7f5eb35329b0.png)

But I get this error when I create an account

`Password: "HelloWorld"`

> Error
> 
> Passwords must have at least one non alphanumeric character.

When I create an account using the console, it is created without any errors using the same password.

What could cause this?

**Comment by klaytaybai** [comment]
@MarneeDear, which version are you using?

**Comment by klaytaybai** [comment]
Are you able to confirm that the user pool information matches what you expect it to be?  I'm not sure why you would be seeing this error.

**Comment by MarneeDear** [comment]
I am using version 1.0.2

**Comment by MarneeDear** [comment]
Have you been able to reproduce it?

**Comment by MarneeDear** [comment]
@klaytaybai Have you been able to reproduce the problem?

**Comment by klaytaybai** [comment]
Hi @MarneeDear, I have reproduced it now.  Thanks for notifying us about this.

**Comment by klaytaybai** [comment]
This has been fixed.  Thanks again for reporting it.

**Comment by MarneeDear** [comment]
Is this fix in version 1.04? I tried upgrading but I am still getting password requirements errors.
